### ISSUE TITLE
executable is not a valid application for this operating system

### ISSUE THREAD

**Issue by ilneroviaggiatore** [obscurename/youtube-dl-gui#15]
Hi.
My system is Window 7 Home Premium 32 bit. Microsoft .NET Framework 4.7.
With youtube-dl-gui.zip v 1.51 i get message "executable is not a valid application for this operating system".
Youtube-dl-gui.zip v 1.52 crash without a message.
With youtube-dl-gui.exe v 1.52 i get message "exception not managed in the application (...) The Octokit file or assembly could not be loaded. Version- 0.24.0.0 (...)".
Youtube-dl-gui.zip v 1.43 work.
Is 32 bit system no longer supported?

Sorry my bad english.

Thanks for help!

**Comment by obscurename** [comment]
Currently, youtube-dl relies on Ocokit to download youtube-dl, which I'm in the process of phasing out of this program in favor of their official API. I do not know if they support 32-bit or not, I wouldn't be surprised if they didn't. Ultimately, just wait for the next verison if the Octokit won't work for you.

As for the Executable not being valid, that's... new. It's not compiled for 64-bit systems, it should support your system.

If downloading the zip file (latest version, specifically), Octokit.dll should be included, otherwise try a previous version.

Though the next update will be pushed and uploaded to this repo, it will cease being updated on this github. The entire project will ultimately be moved to https://github.com/murrty, so lurk around for it. The application will be updated to reflect the new github links and such, so no need to worry if you use the updater.

**Comment by ilneroviaggiatore** [comment]
Thanks!
Then, i'm waiting for the next release. 
Let's hope!

**Comment by obscurename** [comment]
An update was pushed, hopefully that should fix it.

Also, double check youtube-dl.exe make sure it has a file size of at least 7000kb, as it seems that it will sometimes not completely download. Deleting it and redownloading youtube-dl.exe (Optionally, in the settings or restarting to automatically do it for you) should fix that problem.

**Comment by ilneroviaggiatore** [comment]
Hi, both .zip and .exe releases work!
Very thanks!

**Comment by obscurename** [comment]
No problem.
